### ISSUE TITLE
archive.org s3 api Support please 

### ISSUE THREAD

**Issue by billyprice1** [powdahound/s3browser#12]
Please set bucket-name, s3-access-key, and s3-secret-key in config.php added s3 api from archive.org/account/s3.php and changed the bucket url in config.php to .s3.us.archive.org any help thanks
billyprice1

**Comment by powdahound** [comment]
I don't understand what you're referring to here. Can you explain?

**Comment by billyprice1** [comment]
How do i intagre this with archive.org s3 api https://archive.org/help/abouts3.txt here is an example of  the s3 for arcive.org noobkilervip.s3.us.archive.org
https://archive.org/~vmb/abouts3.html

Thanks 
Billyprice1

**Comment by powdahound** [comment]
Hmm, I'm not sure it would work with that S3-like API since this tool expects to be able to get a full list of all the files in an S3 bucket before rendering a page. The archive.org dataset is so big that even if they exposed a full list of files it would be too big to process.

You'd have to troubleshoot the the setup of this yourself to be sure. If you run into more specific issues you can reopen this issue or create new ones. GL!

**Comment by billyprice1** [comment]
Thanks i work on the end point i just found out that it works on http://ibilly-noobkilervip.codeanyapp.com/s3/ with the same api i just rewiere you code and publish it on github to help others and souce you if thats ok

**Comment by powdahound** [comment]
Of course. It's MIT licensed so very open: https://github.com/powdahound/s3browser/blob/master/LICENSE
